### ISSUE TITLE
Script - Import Time Tracking

### ISSUE THREAD

**Issue by daniel-francelino** [daniel-soaress/automation_python#56]
- [x]  Adionar o botão "Clockify" a tela principal;
- [x]  Ao clickar no Botão Clockify deve ser redirecioado a outra Tela onde terá dois botões "Importar Time Tracking", "Gerar Relatório";
- [x]  Na tela de Config, adionar uma nova Tab "Clockify", onde deve ter dois inputs "email" e "password" (deve ter todo o fluxo que nem as outros Inputs);
